import { IMAGES } from 'app/constants';

export const data = [
  {
    id: '01',
    isNew: true,
    caption: "Men's Knit Sweater",
    title: 'Nike Sportswear Tech Pack',
    price: 35.97,
    oldPrice: 40,
    img: IMAGES.pullover,
  },
  {
    id: '02',
    isNew: false,
    caption: "Men's Casual Shirt",
    title: 'Slim Fit Oxford Button-Down Shirt',
    price: 59.99,
    img: IMAGES.casualShirt,
  },
  {
    id: '04',
    isNew: false,
    caption: "Men's Hooded Jacket",
    title: 'Water-Resistant Windbreaker',
    price: 74.95,
    oldPrice: 89.99,
    img: IMAGES.hoodedJacket,
  },
  {
    id: '03',
    isNew: true,
    caption: "Men's Denim Jeans",
    title: 'Slim Fit Stretch Denim',
    price: 59.99,
    oldPrice: 69.99,
    img: IMAGES.denimJeans,
  },
  {
    id: '05',
    isNew: true,
    caption: "Men's Leather Shoes",
    title: 'Classic Brogue Oxford',
    price: 119.99,
    img: IMAGES.leatherShoes,
  },
  {
    id: '06',
    isNew: false,
    caption: "Men's Sport Shorts",
    title: 'Quick-Dry Performance Shorts',
    price: 29.99,
    oldPrice: 34.99,
    img: IMAGES.sportShorts,
  },
  {
    id: '07',
    isNew: true,
    caption: "Men's Polo Shirt",
    title: 'Classic Pique Polo',
    price: 39.99,
    oldPrice: 44.99,
    img: IMAGES.poloShirt,
  },
  {
    id: '08',
    isNew: false,
    caption: "Men's Winter Coat",
    title: 'Insulated Parka with Faux Fur Hood',
    price: 149.99,
    img: IMAGES.winterCoat,
  },
  {
    id: '09',
    isNew: true,
    caption: "Men's Track Pants",
    title: 'Slim Fit Joggers',
    price: 45.99,
    oldPrice: 49.99,
    img: IMAGES.trackPants,
  },
  {
    id: '10',
    isNew: false,
    caption: "Men's Graphic T-Shirt",
    title: 'Abstract Print Cotton Tee',
    price: 24.99,
    oldPrice: 29.99,
    img: IMAGES.graphicTshirt,
  },
];
